### ISSUE TITLE
Can you share the visualization code?

### ISSUE THREAD

**Issue by cq0907** [stone96123/SA-Softmax#1]
![image](https://github.com/stone96123/SA-Softmax/assets/39946114/5ac2ca81-4dcd-4b4d-b103-a497dd21daeb)

Hello, 

I am very honored to read this paper of yours. I am very interested in the visual content. Can you share a copy of the code for this part? It's very useful for my current work by the email(905054970@qq.com). Thank you!

Best regard.

**Comment by stone96123** [comment]
You can refers to this codebase [https://github.com/ZYK100/LLCM/tree/main/Visualization] which including the correspounding  implementation.

**Comment by cq0907** [comment]
> You can refers to this codebase [https://github.com/ZYK100/LLCM/tree/main/Visualization] which including the correspounding implementation.

Ok, thank you!
